default:
  before_script:
    - rustfmt --version
    - rustc --version
    - cargo --version
    - pwd

stages:
  - build

include:
  - local: 'learning/.gitlab-ci.yml'
  - local: 'unit_simple/.gitlab-ci.yml'

